In [1]:
# the first python data science library that we learn is NumPy

In [2]:
import numpy as np

In [3]:
#transforing a list to a numpy array
mylist = [1,2,3]

In [4]:
type(mylist)

list

In [5]:
np.array(mylist)

array([1, 2, 3])

In [6]:
mylist

[1, 2, 3]

In [7]:
myarr = np.array(mylist)

In [8]:
type(myarr)

numpy.ndarray

In [9]:
myarr

array([1, 2, 3])

In [10]:
print(myarr)

[1 2 3]


In [11]:
print(mylist)

[1, 2, 3]


In [12]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]

In [13]:
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [15]:
# numpy already knows that this a 2D array based on how the list 
# my_matrix is defined
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
# np.arange is similar to the range() func in python
# the first 2 params are the starting (inclusive) and ending index (exclusive)
# so [a,b)
# we can also add a step to increment by as our 3rd param
np.arange(0,101,20)

array([  0,  20,  40,  60,  80, 100])

In [22]:
# np.zeros just returns an array filled with FP value zeros
# we can also add a tuple to define a shape for our array e.g. (3,3)
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [24]:
# np.ones just returns an array filled with FP value ones
# we can also add a tuple to define a shape for our array e.g. (3,3)
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [25]:
np.ones(3)

array([1., 1., 1.])

In [28]:
# np.linspace func retuns a squence of evenly spaced FP nums in an array
# the third param is how many evenly spaced nums we want
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [29]:
# how to create an identity matrix
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [31]:
# gives us an array of a size of our choosing and fills it with nums
# from [0,1) in uniform destribution
np.random.rand(1)

array([0.41663837])

In [32]:
np.random.rand(5,2)

array([[0.95752104, 0.14658537],
       [0.77562097, 0.32820367],
       [0.00172041, 0.73341292],
       [0.33094068, 0.04716788],
       [0.55093479, 0.67002571]])

In [34]:
# gives us an array of a size of our choosing and fills it with nums
# in a normal distribution
np.random.randn(1)

array([1.46275449])

In [36]:
np.random.randn(4,4)

array([[-0.46959964,  0.60284116, -0.7031854 , -0.51133432],
       [-0.54190196, -1.01863156,  0.57008047, -0.1808515 ],
       [ 0.67135424, -0.32704469, -0.82976056,  1.27853491],
       [ 0.44482868,  0.70287989,  1.11727856,  1.10616332]])

In [43]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [45]:
arr = np.arange(0,25)

In [46]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [49]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [50]:
ranarr = np.random.randint(0,101,10)

In [51]:
ranarr

array([82, 86, 74, 74, 87, 99, 23,  2, 21, 52])

In [52]:
ranarr.max()

99

In [53]:
ranarr.min()

2

In [55]:
# .argmax() gives us the index for the max element in an array
ranarr.argmax()

5

In [57]:
# .argmin() gives us the index for the max element in an array
ranarr.argmin()

7