In [1]:
# the first python data science library that we learn is NumPy

In [2]:
import numpy as np

In [3]:
#transforing a list to a numpy array
mylist = [1,2,3]

In [4]:
type(mylist)

list

In [5]:
np.array(mylist)

array([1, 2, 3])

In [6]:
mylist

[1, 2, 3]

In [7]:
myarr = np.array(mylist)

In [8]:
type(myarr)

numpy.ndarray

In [9]:
myarr

array([1, 2, 3])

In [10]:
print(myarr)

[1 2 3]


In [11]:
print(mylist)

[1, 2, 3]


In [12]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]

In [13]:
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [15]:
# numpy already knows that this a 2D array based on how the list 
# my_matrix is defined
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
# np.arange is similar to the range() func in python
# the first 2 params are the starting (inclusive) and ending index (exclusive)
# so [a,b)
# we can also add a step to increment by as our 3rd param
np.arange(0,101,20)

array([  0,  20,  40,  60,  80, 100])

In [22]:
# np.zeros just returns an array filled with FP value zeros
# we can also add a tuple to define a shape for our array e.g. (3,3)
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [24]:
# np.ones just returns an array filled with FP value ones
# we can also add a tuple to define a shape for our array e.g. (3,3)
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [25]:
np.ones(3)

array([1., 1., 1.])

In [28]:
# np.linspace func retuns a squence of evenly spaced FP nums in an array
# the third param is how many evenly spaced nums we want
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [29]:
# how to create an identity matrix
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [31]:
# gives us an array of a size of our choosing and fills it with nums
# from [0,1) in uniform destribution
np.random.rand(1)

array([0.41663837])

In [32]:
np.random.rand(5,2)

array([[0.95752104, 0.14658537],
       [0.77562097, 0.32820367],
       [0.00172041, 0.73341292],
       [0.33094068, 0.04716788],
       [0.55093479, 0.67002571]])

In [34]:
# gives us an array of a size of our choosing and fills it with nums
# in a normal distribution
np.random.randn(1)

array([1.46275449])

In [36]:
np.random.randn(4,4)

array([[-0.46959964,  0.60284116, -0.7031854 , -0.51133432],
       [-0.54190196, -1.01863156,  0.57008047, -0.1808515 ],
       [ 0.67135424, -0.32704469, -0.82976056,  1.27853491],
       [ 0.44482868,  0.70287989,  1.11727856,  1.10616332]])

In [43]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [45]:
arr = np.arange(0,25)

In [46]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [49]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [50]:
ranarr = np.random.randint(0,101,10)

In [51]:
ranarr

array([82, 86, 74, 74, 87, 99, 23,  2, 21, 52])

In [52]:
ranarr.max()

99

In [53]:
ranarr.min()

2

In [55]:
# .argmax() gives us the index for the max element in an array
ranarr.argmax()

5

In [57]:
# .argmin() gives us the index for the max element in an array
ranarr.argmin()

7

In [58]:
arr = np.arange(0,11)

In [59]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [60]:
arr[8]

8

In [61]:
arr[1:5]

array([1, 2, 3, 4])

In [62]:
# indexing and selecting a range of elements takes the form
# as the list in python

In [63]:
# with numpy arrays, we can do broadcasting, which is different than the list

In [65]:
# we cant do the following in a normal python list
arr[0:5] = 100

In [66]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [67]:
arr = np.arange(0,11)

In [68]:
slice_of_arr = arr[0:5]

In [69]:
slice_of_arr

array([0, 1, 2, 3, 4])

In [70]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [74]:
# the [:] notation means select everything (everything from the start to end)
slice_of_arr[:] = 99

In [72]:

slice_of_arr

array([99, 99, 99, 99, 99])

In [78]:
# this is an example of the slice_of_arr being an alias to slice of the original array
# slice_of_array is a pointer to a slice of the original array
# we would need to create a new numpy array to prevent this
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [84]:
# creating a new copy array
arr_copy = arr.copy() # the copy method which copies arr and assigns it to arr_copy

In [85]:
arr_copy[:] = 100

In [86]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [87]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [89]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [90]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [91]:
arr_2d.shape #shape is an attribute of numpy arrays, NOT a method, no ()

(3, 3)

In [92]:
#indexing and slicing is similar to 1d arrays

In [93]:
arr_2d[2]

array([35, 40, 45])

In [94]:
#to get the element 25 in our 2d array

In [95]:
arr_2d[1][1] # how its done in java

25

In [96]:
arr_2d[1,1] # the convention in python

25

In [97]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [98]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [99]:
arr = np.arange(1,11)

In [100]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [101]:
# we can prodcast a condition to the arr

In [102]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [103]:
bool_arr = arr > 4

In [105]:
# we can create boolean arr, and broadcast it to the original array
# to filter and only get the elements that satisfy the bool condition (TRUE)
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [106]:
arr[bool_arr] # these are all the elements that are bigger than 4

array([ 5,  6,  7,  8,  9, 10])

In [108]:
arr[arr > 4] #this is typically what we see

array([ 5,  6,  7,  8,  9, 10])

# Numpy Operations

In [111]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [114]:
arr + 5 #numpy array will apply the operation to every element (array + scalar)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [115]:
arr + arr # this can only be done if arrays are the same size

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [116]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [117]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [118]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [119]:
arr / arr

C:\Users\iliaa\AppData\Local\Temp\ipykernel_25836\3001117470.py:1: RuntimeWarning: invalid value encountered in true_divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [120]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [121]:
arr.max()

9

In [126]:
arr2d = np.arange(0,25).reshape(5,5)
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [127]:
arr2d.sum() #returns the sum of all the elements in the 2d array

300

In [130]:
# what if we want the sum for just the columns or rows?
# sum or other operations have axis params
arr2d.sum(axis=0) #perform the operation ACROSS the ROWS
# returns the sum of each COLUMN

array([50, 55, 60, 65, 70])

In [131]:
arr2d.sum(axis=1) #perform the operations ACROSS the COLUMNS
# returns the sum of each ROW

array([ 10,  35,  60,  85, 110])

In [133]:
arr2d.sum(1) # we can also just put the param without the label
# param positional arguments keeps its order

array([ 10,  35,  60,  85, 110])